 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.torneodelpoder.jframes;

import cl.inacap.torneodelpodermodel.dao.GuerreroService;
import cl.inacap.torneodelpodermodel.dto.Guerrero;
import javax.swing.JOptionPane;

/**
 *
 * @author sarayar
 */
public class IngresarGuerreroFrame extends javax.swing.JFrame {

    /**
     * Creates new form IngresarGuerreroFrame
     */
    public IngresarGuerreroFrame() {
        initComponents();
        //Centrar el frame en la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        razaCbx = new javax.swing.JComboBox<>();
        planetaCbx = new javax.swing.JComboBox<>();
        poderPeleaTxt = new javax.swing.JTextField();
        ingresarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Guerrero");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Raza");

        jLabel3.setText("Ki");

        jLabel4.setText("Planeta de Origen");

        razaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        planetaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ingresarBtn.setText("Ingresar");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresarBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTxt)
                            .addComponent(razaCbx, 0, 139, Short.MAX_VALUE)
                            .addComponent(planetaCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poderPeleaTxt))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addComponent(razaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(poderPeleaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(planetaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(ingresarBtn)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO: Cargar Combobox
        //1. Limpiar combobox
        this.razaCbx.removeAllItems();
        this.planetaCbx.removeAllItems();
        //2. Agregar items al combobox
        String[] razas = new String[]{
            "Sayayin", "Terricola", "Namekuseiyin", "Monstruo"
        };
        String[] planetas = new String[]{
            "Tierra", "Vegita", "Namek", "Otro"
        };

        for (String raza : razas) {
            this.razaCbx.addItem(raza);
        }
        for (String planeta : planetas) {
            this.planetaCbx.addItem(planeta);
        }


    }//GEN-LAST:event_formWindowOpened

    private void limpiarFormulario() {
        this.nombreTxt.setText("");
        this.poderPeleaTxt.setText("");
        this.razaCbx.setSelectedIndex(0);
        this.planetaCbx.setSelectedIndex(0);

    }

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        // TODO add your handling code here:
        try {
            Guerrero guerrero = new Guerrero();
            guerrero.setNombre(this.nombreTxt.getText().trim());
            guerrero.setPoderDePelea(Integer
                    .parseInt(this.poderPeleaTxt.getText().trim()));
            guerrero.setPlanetaOrigen(this.planetaCbx
                    .getSelectedItem().toString());
            guerrero.setRaza(this.razaCbx.getSelectedItem().toString());

            GuerreroService guerreroService = new GuerreroService();
            if (guerreroService.ingresarGuerrero(guerrero)) {
                JOptionPane.showMessageDialog(rootPane, "Guerrero Ingresado");
                limpiarFormulario();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "FAIL");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,
                     "Verifique los datos", "Eror de Validación",
                     JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JComboBox<String> planetaCbx;
    private javax.swing.JTextField poderPeleaTxt;
    private javax.swing.JComboBox<String> razaCbx;
    // End of variables declaration//GEN-END:variables
}
