/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.torneodelpoder.jframes;

import cl.inacap.torneodelpodermodel.dao.GuerreroService;
import cl.inacap.torneodelpodermodel.dto.Guerrero;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarayar
 */
public class MostrarGuerrerosFrame extends javax.swing.JFrame {

    /**
     * Creates new form MostrarGuerrerosFrame
     */
    public MostrarGuerrerosFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.guerrerosTable.setModel(new DefaultTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        guerrerosTable = new javax.swing.JTable();
        guerrerosCbx = new javax.swing.JComboBox<>();
        eliminarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mostrar Guerreros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane2.setEnabled(false);

        guerrerosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(guerrerosTable);

        eliminarBtn.setText("Asesinar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(guerrerosCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(eliminarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guerrerosCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarBtn))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTable(){
        GuerreroService guerreroService = new GuerreroService();
        List<Guerrero> guerreros = guerreroService.obtenerGuerreros();
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Raza");
        model.addColumn("Planeta Origen");
        
        for(Guerrero guerrero: guerreros){
            Object[] fila = new Object[4];
            fila[0] = guerrero.getId();
            fila[1] = guerrero.getNombre();
            fila[2] = guerrero.getRaza();
            fila[3] = guerrero.getPlanetaOrigen();
            model.addRow(fila);
        }
        guerrerosTable.setModel(model);
        
    }
    
    private void cargarComboBox(){
        
        this.guerrerosCbx.removeAllItems();
        GuerreroService guerreroService = new GuerreroService();
        List<Guerrero> guerreros =  guerreroService.obtenerGuerreros();
        for(Guerrero guerrero: guerreros){
            this.guerrerosCbx.addItem(guerrero);
        }
        
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //1. Crear el Modelo
        cargarTable();
        cargarComboBox();
    }//GEN-LAST:event_formWindowOpened

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        // TODO add your handling code here:
        //1. Obtener el guerrero seleccionado
        Guerrero guerrero = (Guerrero)this.guerrerosCbx.getSelectedItem();
        
        if(new GuerreroService().eliminarGuerrero(guerrero.getId())){
            this.cargarTable();
            this.cargarComboBox();
            JOptionPane.showMessageDialog(rootPane, "Guerrero Eliminado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "FAIL");
        }
        //2. llamar al service para eliminar
        
    }//GEN-LAST:event_eliminarBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JComboBox<Guerrero> guerrerosCbx;
    private javax.swing.JTable guerrerosTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
